version: '3.4'

services:
  servicea:    
    build:
      context: .
      dockerfile: ./WepAppA/Dockerfile
    depends_on:
    - "servicec"
    - "serviceb"
    environment:
      WebAppCUrl: "http://servicec" 
      ASPNETCORE_URLS: "http://+"
    ports:
        - "32802:80"        
        - "32805:443"
  serviceb:    
    build:
      context: .
      dockerfile: ./WebAppB/Dockerfile    
    ports:
      - "32803:80"
      - "32806:443"
  servicec:    
    build:
      context: .
      dockerfile: ./WebAppC/Dockerfile
    depends_on:
      - "serviceb"
    environment:
      WebAppBUrl: "http://serviceb"      
    ports:
        - "32804:80"
        - "32807:443"
