apiVersion: apps/v1
kind: Deployment
metadata:
  name: demosvc-a
spec:
  selector:
    matchLabels:
      app: demosvc-a
  replicas: 1
  template:
    metadata:
      labels:
        app: demosvc-a
    spec:
      containers:
      - name: demosvc-a
        image: nishantnepal/k8s-svc-a
        imagePullPolicy: Always
        resources:
          requests:
            memory: "250Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "250m"
        ports:
        - containerPort: 80  
        env:
          - name: WebAppBUrl
            value: "http://demosvc-b"  
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
            
---
apiVersion: v1
kind: Service
metadata:
    name: demosvc-a
spec:
    type: ClusterIP
    ports:
    - port: 80 
      targetPort: 80
    selector:
        app: demosvc-a      

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demosvc-b
spec:
  selector:
    matchLabels:
      app: demosvc-b
  replicas: 1
  template:
    metadata:
      labels:
        app: demosvc-b
    spec:
      containers:
      - name: demosvc-b
        image: nishantnepal/k8s-svc-b
        imagePullPolicy: Always
        resources:
          requests:
            memory: "250Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "250m"
        ports:
        - containerPort: 80    
        env:
        - name: WebAppBUrl
          value: "http://demosvc-c"  
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP

---
apiVersion: v1
kind: Service
metadata:
    name: demosvc-b
spec:
    type: ClusterIP
    ports:
    - port: 80 
      targetPort: 80
    selector:
        app: demosvc-b    

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demosvc-c
spec:
  selector:
    matchLabels:
      app: demosvc-c
  replicas: 1
  template:
    metadata:
      labels:
        app: demosvc-c
    spec:
      containers:
      - name: demosvc-c
        image: nishantnepal/k8s-svc-c
        imagePullPolicy: Always
        resources:
          requests:
            memory: "250Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "250m"
        ports:
        - containerPort: 80    
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP   

---
apiVersion: v1
kind: Service
metadata:
    name: demosvc-c
spec:
    type: ClusterIP
    ports:
    - port: 80 
      targetPort: 80
    selector:
        app: demosvc-c
