{{- if .Values.secrets.enabled -}}
{{- $fullName := include "helm.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
 name: {{ $fullName }}
 labels:
    {{- include "helm.labels" . | nindent 4 }}
type: Opaque
stringData:
  DemoAppSettingKey: "from secret"
  MySuperSecretKey: {{ .Values.secrets.mySuperSecretKey }}
{{- end }}  